apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-debug
spec:
  selector:
    matchLabels:
      app: http-debug
  template:
    metadata:
      labels:
        app: http-debug
    spec:
      containers:
      - name: http-debug
        image: lishijun01/http-debug:0.0.1
        ports:
        - containerPort: 9001
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: 9001
          initialDelaySeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 9001
---

apiVersion: v1
kind: Service
metadata:
  name: http-debug
spec:
  selector:
    app: http-debug
  ports:
  - port: 80
    targetPort: 9001
  type: LoadBalancer
